---
title: "logit2"
author: "Eung Kyu Kim"
date: "October 19, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}



library(ggplot2)
library(tidyverse)
library(aod)


ps2_ex <-ps2_data %>%
  
  select(age, feelings_life, self_rated_health, self_rated_mental_health, 
         income_family, income_respondent, average_hours_worked, total_children, 
         total_children) %>%
  
  mutate(feelings_life = case_when(
    feelings_life=="1" ~ as.numeric(0),
    feelings_life=="2" ~ as.numeric(0),
    feelings_life=="3" ~ as.numeric(0),
    feelings_life=="4" ~ as.numeric(0),
    feelings_life=="5" ~ as.numeric(0),
    feelings_life=="6" ~ as.numeric(1),
    feelings_life=="7" ~ as.numeric(1),
    feelings_life=="8" ~ as.numeric(1),
    feelings_life=="9" ~ as.numeric(1),
    feelings_life=="10" ~ as.numeric(1)
    
  ))

ps2_ex_complete <- na.omit(ps2_ex)


ps2_ex_complete$self_rated_health<- factor(ps2_ex_complete$self_rated_health)

mylogit2 <- glm(feelings_life ~ age + total_children + self_rated_health, data = ps2_ex_complete, family = "binomial")

summary(mylogit2)

```


```{r}
confint(mylogit2)
confint.default(mylogit2)
```

```{r}
#wald test for income

wald.test(b = coef(mylogit2), Sigma = vcov(mylogit2), Terms = 4:7)


#Chi-Squared Test
#X2 = 51.1, df = 5, P(> X2) = 8.1e-10
```
```{r}
exp(coef(mylogit2))


exp(cbind(OR = coef(mylogit2), confint(mylogit2)))
```

```{r}

newdata2 <- with(ps2_ex_complete, data.frame(age= mean(age), total_children = mean(total_children), self_rated_health = factor(1:5)))

newdata2$rankP <- predict(mylogit2, newdata = newdata2, type = "response")
newdata2
```




```{r}
newdata22 <- with(ps2_ex_complete, data.frame(total_children = rep(seq(from = 0, to = 9, length.out= 10),5), 
                                              age = mean(age),
                                              self_rated_health = factor(rep(1:5, each = 100))))



newdata222 <- cbind(newdata22, predict(mylogit2, newdata = newdata22, type = "link",
                                       se = TRUE))
newdata222 <- within(newdata222, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

head(newdata222)



ggplot(newdata222, aes(x = total_children, y = PredictedProb)) + geom_ribbon (aes(ymin = LL,
                                                                       ymax = UL, fill = self_rated_health), alpha = 0.2) +
        geom_line(aes(colour = self_rated_health),
                  size = 1) +
      xlab("Total Number of Children") +
      ylab("Predicted Probability of Being Happy") +
      ggtitle("Plot of Probabilities of Being Happy Considering the 
              Differences of Self Rated Health and Total Number of Children ")
```