---
title: "asd"
author: "Eung Kyu Kim"
date: "October 19, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

#install.packages('aod')

library(ggplot2)
library(tidyverse)
library(aod)


ps2_ex <-ps2_data %>%
  
  select(age, feelings_life, self_rated_health, self_rated_mental_health, 
         income_family, income_respondent, average_hours_worked, total_children, 
         total_children) %>%
  
  mutate(feelings_life = case_when(
    feelings_life=="1" ~ as.numeric(0),
    feelings_life=="2" ~ as.numeric(0),
    feelings_life=="3" ~ as.numeric(0),
    feelings_life=="4" ~ as.numeric(0),
    feelings_life=="5" ~ as.numeric(0),
    feelings_life=="6" ~ as.numeric(1),
    feelings_life=="7" ~ as.numeric(1),
    feelings_life=="8" ~ as.numeric(1),
    feelings_life=="9" ~ as.numeric(1),
    feelings_life=="10" ~ as.numeric(1)
    
  ))

ps2_ex_complete_logit1 <- na.omit(ps2_ex)


ps2_ex_complete_logit1$income_respondent<- factor(ps2_ex_complete_logit1$income_respondent)

mylogit <- glm(feelings_life ~ age + total_children + income_respondent, data = ps2_ex_complete_logit1, family = "binomial")

summary(mylogit)

```


```{r}
confint(mylogit)
confint.default(mylogit)
```

```{r}
#wald test for income

wald.test(b = coef(mylogit), Sigma = vcov(mylogit), Terms = 4:8)


#Chi-Squared Test
#X2 = 51.1, df = 5, P(> X2) = 8.1e-10
```
```{r}
exp(coef(mylogit))


exp(cbind(OR = coef(mylogit), confint(mylogit)))
```

```{r}

newdata1 <- with(ps2_ex_complete_logit1, data.frame(age= mean(age), total_children = mean(total_children), income_respondent = factor(1:5)))

newdata1$rankP <- predict(mylogit, newdata = newdata1, type = "response")
newdata1
```


```{r}
newdata11 <- with(ps2_ex_complete_logit1, data.frame(age = rep(seq(from = 1, to = 100, length.out= 100),5), 
                                              total_children = mean(total_children),
                                              income_respondent = factor(rep(1:5, each = 100))))



newdata111 <- cbind(newdata11, predict(mylogit, newdata = newdata11, type = "link",
                                       se = TRUE))
newdata111 <- within(newdata111, {
  PredictedProb <- plogis(fit)
  LL <- plogis(fit - (1.96 * se.fit))
  UL <- plogis(fit + (1.96 * se.fit))
})

#head(newdata111)



ggplot(newdata111, aes(x = age, y = PredictedProb)) +
        geom_ribbon (aes(ymin = LL,
                         ymax = UL, fill = income_respondent), alpha = 0.2) +
        geom_line(aes(colour = income_respondent),
                  size = 1) +
      xlab("Age of Respondents") +
      ylab("Predicted Probability of Being Happy") +
      ggtitle("Plot of Probabilities of Being Happy Considering the 
              Differences of Income and Age") +
      scale_fill_discrete(name = "Income of Respondents" , labels = c("Less than $25,000", "$25,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999", "$100,000 to $ 124,999"))
  
      
```

